jobs:
  dangermattic:
    if: ${{ (github.event.pull_request.draft == false) || (github.event.pull_request.draft
      == true && contains(fromJSON('["opened", "synchronize"]'), github.event.action))
      }}
    secrets:
      github-token: ${{ secrets.DANGERMATTIC_GITHUB_TOKEN }}
    uses: Automattic/dangermattic/.github/workflows/reusable-run-danger.yml@v1.0.0
name: "\u2622\uFE0F Danger"
on:
  repository_dispatch:
    types: trigger-ga___run-danger.yml
