jobs:
  check-labels-on-issues:
    secrets:
      github-token: ${{ secrets.DANGERMATTIC_GITHUB_TOKEN }}
    uses: Automattic/dangermattic/.github/workflows/reusable-check-labels-on-issues.yml@v1.0.0
    with:
      label-error-message: "\U0001F6AB Please add a type label (e.g. **[Type] Enhancement**)\
        \ and a feature label (e.g. **Stats**) to this issue."
      label-format-list: '[ "^\[.+\]", "^[[:alnum:]]" ]'
      label-success-message: "Thanks for reporting! \U0001F44D"
name: "\U0001F4DD Validate Issues"
on:
  repository_dispatch:
    types: trigger-ga___validate-issues.yml
